services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toolbox
    ports:
      - "8585:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - plantuml
      - scanner

  plantuml:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    restart: unless-stopped
    environment:
      - PLANTUML_LIMIT_SIZE=8192